### ISSUE TITLE
Error SQL syntax

### ISSUE THREAD

**Issue by oculos** [ameerkat/imdb-to-sql#10]
I get the following error: 
```
__main__ [status]: using python regex parsing code.
tosql.py:287: Warning: Field 'gender' doesn't have a default value
  connection_cursor.execute(build_insert_query(name, param_dict))
Traceback (most recent call last):
  File "tosql.py", line 550, in <module>
    billing_position}, skip_lookup = True, supress_output = True)
  File "tosql.py", line 287, in select_or_insert
    connection_cursor.execute(build_insert_query(name, param_dict))
  File "build/bdist.macosx-10.12-intel/egg/MySQLdb/cursors.py", line 205, in execute
  File "build/bdist.macosx-10.12-intel/egg/MySQLdb/connections.py", line 36, in defaulterrorhandler
_mysql_exceptions.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'character) VALUES (1, 1, 'Goth raver')' at line 1")
``` 

Any clue what I can do to fix it?

**Comment by LorenzBuehmann** [comment]
The converter is for SQLLite and PostgreSQL, not for MySQL databases.

**Comment by markjin1990** [comment]
Same problem here. Are you suggesting that this project is not yet ready for mysql? Thanks.

**Comment by ameerkat** [comment]
I do have a MySQL converter, which was working previously. I'll take a look soon.
