### ISSUE TITLE
while connecting to mysql

### ISSUE THREAD

**Issue by manojprithvee** [ameerkat/imdb-to-sql#9]
tosql.py:162: Warning: Changing sql mode 'NO_AUTO_CREATE_USER' is deprecated. It will be removed in a future release.
  c.execute(query.strip())
__main__ [status]: using python regex parsing code.
tosql.py:287: Warning: Field 'gender' doesn't have a default value
  connection_cursor.execute(build_insert_query(name, param_dict))
Traceback (most recent call last):
  File "tosql.py", line 550, in <module>
    billing_position}, skip_lookup = True, supress_output = True)
  File "tosql.py", line 287, in select_or_insert
    connection_cursor.execute(build_insert_query(name, param_dict))
  File "/Users/manoj/programming/python/Watchseries-Downloader/venv/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/Users/manoj/programming/python/Watchseries-Downloader/venv/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
_mysql_exceptions.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'character) VALUES (1, 1, 'Goth raver')' at line 1")

**Comment by LorenzBuehmann** [comment]
The converter is for SQLLite and PostgreSQL, not for MySQL databases.
